name: "Zigbee2MQTT ZBOSS (ESP32-C6)"
version: "1.0.0"
slug: "zboss_zigbee2mqtt"
description: "Zigbee2MQTT com suporte nativo ZBOSS para ESP32-C6 (patch tostmann)"
url: "https://github.com/wesioplayconstructor/zboss-zigbee2mqtt-app"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
host_network: true
uart: true
udev: true
hassio_api: true
ingress: true
ingress_port: 8099
panel_icon: "mdi:zigbee"
panel_title: "Zigbee2MQTT"
services:
  - "mqtt:need"
ports:
  8485/tcp: 8485
  8099/tcp: null
options:
  data_path: /config/zigbee2mqtt
  socat:
    enabled: false
    master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
    slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
    options: "-d -d"
    log: false
  mqtt: {}
  serial:
    port: /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_98:A3:16:BF:20:A0-if00
    adapter: zboss
    baudrate: 115200
    rtscts: false
schema:
  data_path: str
  socat:
    enabled: bool
    master: str
    slave: str
    options: str
    log: bool
  mqtt:
    server: "str?"
    ca: "str?"
    key: "str?"
    cert: "str?"
    user: "str?"
    password: "str?"
    base_topic: "str?"
  serial:
    port: "str?"
    adapter: "match(zstack|deconz|zigate|ezsp|ember|zboss)?"
    baudrate: "int?"
    rtscts: "bool?"
  watchdog: "str?"
  force_onboarding: "bool?"
