FROM ghcr.io/tostmann/zigbee2mqtt-esp32:latest

# Persistent data directory under Home Assistant config folder
ENV ZIGBEE2MQTT_DATA=/config/zigbee2mqtt
ENV Z2M_DATA=/config/zigbee2mqtt

WORKDIR /config/zigbee2mqtt
